const menu = [
    {
        id: 1,
        title: 'american breakfast',
        category: 'breakfast & brunch',
        price: 15.99,
        img: 'https://cookinglowkey.com/wp-content/uploads/2020/04/Low-Key-Classic-Breakfast.jpg',
        desc: `A classic American breakfast platter featuring scrambled eggs, a butter croissant, roma tomatoes, and applewood smoked bacon.`,
        ingredients: `Scrambled Eggs: Liquid Whole Egg: Whole Egg, Citric Acid, 0.15% Water Added As Carrier For Citric Acid. Citric Acid Added To Preserve Color., Cottonseed Cooking Oil: Cottonseed Oil And Dimethylpolysiloxane Added To Reduce Foaming., Butter Croissant: Unbleached Enriched Flour, Water, Butter, Yeast, Sugar, Liquid Whole Eggs, Salt, Malted Wheat Flour, Malted Barley Extract, Wheat Gluten, Food Enzymes (Xylanase, Amylase), Ascorbic Acid, Dried Whole Eggs, Skim Milk Powder, Soy Flour., Roma Tomatoes: Tomato, Roma, Applewood Smoked Bacon: Cured With: Water, Salt, Sugar, Sodium Phosphates, Sodium Erythorbate, Sodium Nitrite.`,
    },
    {
        id: 2,
        title: 'croque madame',
        category: 'breakfast & brunch',
        price: 13.99,
        img: 'https://www.foodandwine.com/thmb/xM-KOuy_eX8jUJHzXjMBu7xAYxA=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/croque-madame-FT-RECIPE0222-2da2bb82f1004613b0c65bad6e2fceb5.jpg',
        desc: `A classic French grilled ham and cheese sandwich topped with a fried egg, served with a side of mesclun mixed greens and balsamic dressing.`,
        ingredients: `(Pasteurized Whole Milk, Vitamin D), Heavy Cream (Cream, Carrageenan, Cellulose Gum, Polysorbate 80, Guar Gum) Canola Oil, Romano Cheese [Pasteurized Sheep's And Cow's Milk, Rennet, Salt, Natamycin (Mold Inhibitor)], Parmesan Cheese (Milk, Cheese Culture, Salt Enzymes), Chicken Base [Roasted Chicken, Salt, Maltodextrin, Yeast Extract, Chicken Fat, Corn Starch, Sugar, Onion Powder, Turmeric (Color), Natural Flavor], Modified Food Starch, All Purpose Flour, Dairy Stabilizer [Coconut Oil, Food Starch Modified, Corn Syrup Solids.`,
    },
    {
        id: 3,
        title: 'avocado toast',
        category: 'breakfast & brunch',
        price: 6.99,
        img: 'https://www.eatingwell.com/thmb/nKFXLVvBA7Ojq7Dd9xs9ieuuRj8=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/EatingWell-April-Avocado-Toast-Beauty-Angle-1x1-5dbdcb43cc6a43d588a620fdb9a42bf4.jpg',
        desc: `Smashed avocado spread on toasted panini bread, topped with lemon juice, coarse sea salt, and cracked black pepper. A simple yet delicious vegetarian breakfast or snack.`,
        ingredients: `Avocado: Avocado, Ripe, Panini Bread: Flour (Wheat, Malted Barley), Water, Salt, Yeast, Contains Less Than 2% Of : Monocalcium Phosphate, Corn Starch, Monodiglycerides, Enzymes, Ascorbic Acid, Potassium Iodate, And Calcium Propionate/, Extra Virgin Olive Oil, Lemon: Lemon, Coarse Sea Salt: Sea Salt, Yellow Prussiate Of Soda To Prevent Caking., Ground Black Pepper: Black Pepper`,

    },
    {
        id: 4,
        title: 'corn chowder soup',
        category: 'soups',
        price: 20.99,
        img: 'https://www.allrecipes.com/thmb/QyKPyejIZeSt1YchzQwJ_yA3PWI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/86096-grandmas-corn-chowder-ddmfs-3x4_9570-3c93413e70c840c6b061a2bd47ca677d.jpg',
        desc: `A rich and creamy corn chowder soup made with fresh corn, potatoes, celery, and onions in a savory broth.`,
        ingredients: `Corn Chowder Soupe: Water, Whole Milk (Pasteurized Whole Milk, Vitamin D), Corn, Heavy Cream (Cream, Carrageenan, Cellulose Gum, Polysorbate 80, Guar Gum), Potatoes, Celery, Onions, Modified Food Starch, Sugar, Salt, Canola Oil, Cultured Grade A Non-Fat Dry Milk Powder, Xanthan Gum, Spices.`,
    },
    {
        id: 5,
        title: 'country potato soup',
        category: 'soups',
        price: 22.99,
        img: 'https://www.mcalistersdeli.com/-/media/mcalisters/menu/soups/soups_country-potato-cup_thumbnail-664x440.jpg?v=1&d=20200601T133501Z',
        desc: `A hearty and comforting potato soup with chunks of potatoes, leeks, onions, and smoky bacon in a creamy broth.`,
        ingredients: `Soup, Potato: Water, Potatoes, Cream (Pasteurized Cream, Whole Milk), Leeks, Onions, Butter (Pasteurized Sweet Cream, Natural Flavorings), Salt, Chicken Base [Roasted Chicken, Salt, Maltodextrin, Yeast Extract, Chicken Fat, Corn Starch, Sugar, Onion Powder, Turmeric (Color), Natural Favor], Corn Starch, Spices., Mild Cheddar Cheese (Shredded): Pasteurized Milk, Cheese Culture, Salt, Enzymes And Annatto (If Colored). Potato Starch And Powdered Cellulose Added To Prevent Caking., Applewood Smoked Bacon: Cured With: Water, Salt, Sugar, Sodium Phosphates, Sodium Erythorbate, Sodium Nitrite`,
    },
    {
        id: 6,
        title: 'french onion soup',
        category: 'soups',
        price: 18.99,
        img: 'https://www.onceuponachef.com/images/2019/02/french-onion-soup-1.jpg',
        desc: `A classic French onion soup made with caramelized onions simmered in a rich beef broth, topped with a toasted baguette and melted Swiss cheese.`,
        ingredients: `Soup, French Onion: Water, Onions, Red Wine*, Beef Base [Roasted Beef And Beef Stock, Salt, Hydrolyzed Corn Protein, Beef Type Favor (Hydrolyzed Corn Gluten, Corn Syrup Solids, Thiamine Hydrochloride), Corn Starch, Caramel Color (Class 1), Sugar, Flavorings, Contains 2% Or Less Of Disodium Inosinate, Disodium Guanylate, Yeast Extract, Lactic Acid, Calcium Lactate, Xanthan Gum, Beef Extract, Spice. *Except For The Small Amount Naturally Occurring In The Hydrolyzed Corn Protein And Yeast Extract], Canola Oil, Garlic, Olive Oil, Spices., Swiss Cheese (Shredded): Pasteurized Part-Skim Milk, Cheese Culture, Salt, Enzymes. Potato Starch, Powdered Cellulose Added To Prevent Caking., Crouton Soup: Baguette: Enriched Unbleached Flour (Wheat Flour, Niacin, Reduced Iron, Thiamin Mononitrate, Riboflavin, Folic Acid), Water, Sourdough [Enriched Unbleached Flour (Wheat Flour, Niacin, Reduced Iron, Thiamin Mononitrate, Riboflavin, Folic Acid), Water], Contains Less Than 2% Of The Following: Sea Salt, Yeast, Malted Barley Flour., Olive Oil Blend: 80% Soybean Oil, 20% Olive Pomace Oil, Chopped Garlic: Garlic, Water, Phosphoric Acid, Sodium Benzoate And Potassium Sorbate (Preservatives). Contains: Naturally Occurring Sulfites.`,
    },
    {
        id: 7,
        title: 'chicken salad',
        category: 'salads',
        price: 8.99,
        img: 'https://www.skinnytaste.com/wp-content/uploads/2008/07/Classic-Chicken-Salad-4.jpg',
        desc: 'A classic chicken salad made with diced balsamic chicken breast, celery, mayonnaise, and seasoned bread crumbs.',
        ingredients: `Chicken Salade: Balsamic Chicken Breast: Powder, Sugar, Olive Oil, Dried Parsley, Natural Flavors, 2% Or Less Citric Acid], Vinegar, Corn Starch, Cultured Dextrose, Chicken Flavor [Salt, Dried Chicken Stock, Natural Flavors, Corn Starch, Dried Onion, Chicken Fat, Yeast Extract, Dried Garlic, 2% Or Less Rosemary Extract (To Protect Flavor)], Balsamic Vinegar Flavor Type (Gum Arabic, Natural Flavor, Soybean Oil), Natural Flavors, Salt, Chicken Broth., Celery: Celery, Diced, Mayonnaise: Soybean Oil, Water, Egg Yolks, Distilled Vinegar. Contains 2%Or Less Of Salt, Sugar, Mustard Seed, Calcium Disodium Edta Added To Protect Flavor. Contains: Egg., Bread Crumbs: Enriched Wheat Flour (Flour, Malted Barley Flour, Reduced Iron, Niacin, Thiamine Mononitrate, Riboflavin, Folic Acid), Water, High Fructose Corn Syrup, Yeast, Soybean Oil, Salt., Chicken Base: Roasted Chicken And Chicken Juices, Salt, Sugar, Corn Starch, Chicken Fat, Dehydrated Onion, Turmeric, Flavoring., Ground Black Pepper: Black Pepper`,
    },
    {
        id: 8,
        title: 'petite field greens salad',
        category: 'salads',
        price: 12.99,
        img: 'https://order.lamadeleine.com/usercontent/product_sub_img/LAM102911-ProductTile-1200x900_PetiteFieldGreensSalade-01-KF.jpg',
        desc: 'A fresh and light salad made with mixed field greens, tossed in a tangy French vinaigrette dressing.',
        ingredients: `Petite Field Greens Salade: Mesculine Mixed Lettuce: Lettuce, Mesculine Mixed, French Vinaigrette Dressing: Canola Oil, Water, Extra Virgin Olive Oil, Red Wine Vinegar*, Dijon Mustard (Distilled Vinegar, Water, Mustard Seed, Salt, White Wine, Citric Acid, Turmeric, Spices), Sugar, Shallots, Cultured Dextrose, Salt, Spices, Xanthan Gum.`,
    },
    {
        id: 9,
        title: 'kale & quinoa salad',
        category: 'salads',
        price: 9.99,
        img: 'https://www.eatingwell.com/thmb/H8ldmJ7nz2tNtBsYHNYLTpGbRKc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/kale-and-quinoa-salad-with-lemon-dressing-50e7ff379b924df8ab3dd665e2efefb5.jpg',
        desc: 'A nutrient-packed salad with kale, quinoa, feta cheese, dried cranberries, roasted pecans, and a balsamic dressing. A delicious and healthy option.',
        ingredients: `Kale & Quinoa Salade: Plain Quinoa: Cooked Quinoa: Quinoa, Balsamic Dressing: Vegetable Oil (Canola Oil), Balsamic Vinegar, Extra Virgin Olive Oil, Water, Dijon Mustard (Distilled Vinegar, Water, Mustard Seed, Salt, White Wine*, Citric Acid, Turmeric, Spices), Salt, Mustard Flour, Spice., Feta Crumbles: Feta Cheese (Cultured Pasteurized Milk, Salt, Enzymes), Powdered Cellulose (To Prevent Caking), Natamycin (A Natural Mold Inhibitor). Milk, Dried Cranberry: Cranberries, Sugar, Sunflower Oil., Kale: Kale, Chopped, Roasted Pecan Nuts: Pecans, Green Onions: Onions, Green, Olive Oil Blend: 80% Soybean Oil, 20% Olive Pomace Oil, Granulated Iodized Salt: Salt, Sodium Silicoaluminate, Dextrose, Potassium Iodine And Sodium Bicarbonate, Ground Black Pepper: Black Pepper`,
    },
    {
        id: 10,
        title: 'baguette sandwich',
        category: 'sandwiches',
        price: 9.99,
        img: 'https://gethealthyu.com/wp-content/uploads/2021/11/Veggie-Baguett-Sandwich.png',
        desc: 'A classic baguette sandwich filled with your choice of delicious ingredients.',
        ingredients: `Kale & Quinoa Salade: Plain Quinoa: Cooked Quinoa: Quinoa, Balsamic Dressing: Vegetable Oil (Canola Oil), Balsamic Vinegar, Extra Virgin Olive Oil, Water, Dijon Mustard (Distilled Vinegar, Water, Mustard Seed, Salt, White Wine*, Citric Acid, Turmeric, Spices), Salt, Mustard Flour, Spice., Feta Crumbles: Feta Cheese (Cultured Pasteurized Milk, Salt, Enzymes), Powdered Cellulose (To Prevent Caking), Natamycin (A Natural Mold Inhibitor). Milk, Dried Cranberry: Cranberries, Sugar, Sunflower Oil., Kale: Kale, Chopped, Roasted Pecan Nuts: Pecans, Green Onions: Onions, Green, Olive Oil Blend: 80% Soybean Oil, 20% Olive Pomace Oil, Granulated Iodized Salt: Salt, Sodium Silicoaluminate, Dextrose, Potassium Iodine And Sodium Bicarbonate, Ground Black Pepper: Black Pepper`,
    },
    {
        id: 11,
        title: 'chicken riviera sandwich',
        category: 'sandwiches',
        price: 8.99,
        img: 'https://order.lamadeleine.com/usercontent/product_sub_img/LMD_042220_SpringSmrDigital_PT0002_1bd11.jpg',
        desc: 'A flavorful sandwich made with balsamic chicken breast, avocado, basil pesto, applewood smoked bacon, and melted Swiss cheese on rustic ciabatta bread.',
        ingredients: `Rustic Ciabatta: Unbleached Enriched Flour (Wheat Flour, Niacin, Reduced Iron, Thiamin Mononitrate, Riboflavin, Folic Acid), Water, Salt, Canola Oil, Dried Vinegar, Yeast, Malted Wheat Flour, Malted Barley Flour, Ascorbic Acid, Foods Enzymes (Xylanase, Glucose-Oxydase, Lipase, Alpha-Amylase)., Balsamic Chicken Breast: Powder, Sugar, Olive Oil, Dried Parsley, Natural Flavors, 2% Or Less Citric Acid], Vinegar, Corn Starch, Cultured Dextrose, Chicken Flavor [Salt, Dried Chicken Stock, Natural Flavors, Corn Starch, Dried Onion, Chicken Fat, Yeast Extract, Dried Garlic, 2% Or Less Rosemary Extract (To Protect Flavor)].`,
    },
    {
        id: 12,
        title: 'french dip sandwich',
        category: 'sandwiches',
        price: 10.99,
        img: 'https://www.allrecipes.com/thmb/8iPnxpoReUw_nOq5OJob9u2UL3E=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/136476-Easy-French-Dip-Sandwiches-ddmps-4x3-104757-5b722084131b4259a91e073b0ae539ba.jpg',
        desc: 'A classic French dip sandwich featuring thinly sliced roast beef piled onto a toasted baguette and served with a flavorful au jus dipping sauce on the side.',
        ingredients: `Au Jus: Water: Water, Au Jus Gravy Mix: Maltodextrin, Modified Corn Starch, Hydrolyzed Soy Protein, Yeast Extract, Salt, Onion Powder, Caramel Color, Brown Sugar, Beef Fat, Lard, Natural Flavors, Citric Acid, Beef Extract, Disodium Guanylate, Disodium Inosinate. Contains: Soy, Sulfites, Caramelized Onions: Cooked Onion: Cooked Onion, Cottonseed Cooking Oil: Cottonseed Oil And Dimethylpolysiloxane Added To Reduce Foaming., Ground Black Pepper: Black Pepper, Granulated Iodized Salt: Salt, Sodium Silicoaluminate.`,
    },
    {
        id: 13,
        title: '4 cheese baked pasta',
        category: 'entrees & pastas',
        price: 20.99,
        img: 'https://res.cloudinary.com/hksqkdlah/image/upload/5665_sfs-fm07-rcp-4c-baked-cheese-penne-c-001-291535.jpg',
        desc: 'A rich and creamy baked pasta dish featuring a blend of four kinds of melted cheeses - gruyere, American, asiago, and parmesan - tossed with penne pasta and served with a toasted sea salt baguette.',
        ingredients: `Cheese Sauce: Four Cheese Sauce (Gruyere): WATER, milk, skim, with vitamins A & D, cheese, swiss, Unsalted butter (pasteurized sweet cream), salt., White Pasteurized Process American Cheese (cultured milk, water, cream, sodium phosphate, salt, titanium dioxide (color), enzymes), HEAVY CREAM (cream, carrageenan, cellulose gum, polysorbate 80, guar gum), starch, food, modified, Frigex, W, Asiago Cheese (pasteurized cow's milk, cheese cultures, salt, enzymes), Cultured Dextrose (maltodextrin, cultured dextrose).`,
    },
    {
        id: 14,
        title: 'chicken friand',
        category: 'entrees & pastas',
        price: 16.99,
        img: 'https://seasonandthyme.com/wp-content/uploads/2022/06/chicken-friand-featured-1024x1024.jpg',
        desc: `Succulent chicken breast enveloped in flaky pastry, a savory delight in every bite.`,
        ingredients: `Chicken Friand: Puff Pastry: Unbleached Enriched Wheat Flour (Flour, Niacin, Reduced Iron, Thiamine Mononitrate [Vitamin B1], Riboflavin [Vitamin B2], Folic Acid), Water, Vegetable Oils (Palm, Soybean, Hydrogenated Cottonseed), Contains 2 Percent Or Less Of: High Fructose Corn Syrup, Salt, Mono And Diglycerides, Soy Lecithin, Malted Barley Flour, Turmeric And Annatto Extracts For Color., Chicken Friand Filling: Balsamic Chicken Breast: Powder, Sugar, Olive Oil, Dried Parsley, Natural Flavors, 2% Or Less Citric Acid].`,
    },
    {
        id: 15,
        title: 'pesto caprese crepe',
        category: 'entrees & pastas',
        price: 17.99,
        img: 'https://www.vanillabeancuisine.com/wp-content/uploads/2022/09/Caprese-Crepes-FEAT-IMAGE.jpg',
        desc: `Fresh basil pesto, juicy tomatoes, and creamy mozzarella nestled in delicate crepes, a taste of Italy in every fold.`,
        ingredients: `Pesto Caprese Crepe: Thin Slice Mozzarella Cheese: PASTEURIZED MILK, VINEGAR, ENZYMES, SALT, Crepe Shell: Durum wheat flour, water, eggs, whole milk (milk, vitamin D3 added), soybean oil, dry vegetable oil (coconut oil, lactose, sodium caseinate (a milk derivative), dipotassium phosphate), sugar, salt., Roma Tomatoes: Tomato, Roma, Basil Pesto Sauce: Basil Slurry (Basil, Canola Oil, Water, Salt, Ascorbic Acid), Romano Cheese [Pasteurized Sheep's and Cow's Milk, Rennet, Salt, Natamycin (Mold Inhibitor)], Garlic, Salt, Cultured Dextrose (Natural Antimicrobial)., Granulated Iodized Salt: Salt, Sodium Silicoaluminate, Dextrose, Potassium Iodine And Sodium Bicarbonate, Roma Tomatoes: Tomato, Roma, Balsamic Glaze: Balsamic Vinegar Of Modena (Wine Vinegar, Cooked Grape Must) 61%, Cooked Grape Must, Sugar, Stabilizer: Xantan Gum, Parsley: Parsley`,
    },
    {
        id: 16,
        title: 'chocolate chunk cookie',
        category: 'bakery',
        price: 5.99,
        img: 'https://img.buzzfeed.com/thumbnailer-prod-us-east-1/video-api/assets/62298.jpg',
        desc: `Indulge in the perfect balance of rich chocolate chunks and buttery goodness in every bite of our classic chocolate chunk cookie.`,
        ingredients: `Enriched Bleached Flour (Wheat Flour, Niacin, Reduced Iron, Thiamin Mononitrate, Riboflavin, Folic Acid), Chocolate Chunks (Sugar, Chocolate Liquor, Cocoa Butter, Milk Fot, Soy Lecithin (An Emulsifier) Salt And Vainilla) Butter (Milk), Brown Sugar, Sugar, Eggs, Baking Soda, Salt, Natural Flavors`,
    },
    {
        id: 17,
        title: 'macarons',
        category: 'bakery',
        price: 7.99,
        img: 'https://images.immediate.co.uk/production/volatile/sites/2/2022/05/Macarons-fb56db8.jpg?quality=90&resize=556,505',
        desc: `Experience the delicate elegance of our handcrafted macarons, bursting with vibrant flavors and melt-in-your-mouth goodness.`,
        ingredients: `Macaron - Chocolate: Icing sugar (sugar, potato starch), almond powder, chocolate (cocoa paste, sugar, cocoa butter, soy lecithin, natural vanilla flavor), egg whites, milk, sugar, butter (cream), reduced fat cocoa powder, caramel color, juice concentrates (beetroot, acerola, lemon), apricot purée (apricots, ascorbic acid, citric acid).`,
    },
    {
        id: 18,
        title: 'palmier',
        category: 'bakery',
        price: 6.99,
        img: 'https://www.letthemeatgfcake.com/wp-content/uploads/2021/01/IMG_8331-1.jpg',
        desc: `Savor the crisp, golden layers of our palmier, a sweet treat that delicately melts on your tongue with every bite.`,
        ingredients: `Palmier Dough: Untreated Unbleached Enriched Flour (Wheat Flour, Niacin, Reduced Iron, Thiamin Mononitrate, Riboflavin, Folic Acid), Non-Hydrogenated Vegatable Oil Margarine (Modified Palm And Palm Oil, Canola Oil, Vegatable Monoglycerides, Soybean Lecithin, Potassium Sorbate, Artificial Flavor, Citric Acid, Vitamin A Palmitate, Beta-Carotene, Vitamin D), Water, Non-Hydrogenated Vegatable Oil Margarine (Modified Palm And Palm Oil, Canola Oil, Vegatable Monoglycerides, Soybean Lecithin, Potassium Sorbate, Artificial Flavor, Citric Acid, Vitamin A Palmitate, Beta-Carotene), Sugar, Salt, Granulated Xfine Cane Sugar: Cane Sugar, Pan Coating Oil: Water, Canola Oil*, Soy Lecithin, Sorbic Acid, & Potassium Sorbate (Preservatives), Beta Carotene (Color), Propellant. Contains Soy. *Adds A Trivial Amount Of Fat.`,
    },
    {
        id: 19,
        title: 'american roast coffee',
        category: 'drinks',
        price: 4.99,
        img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/A_small_cup_of_coffee.JPG/1200px-A_small_cup_of_coffee.JPG',
        desc: `Awaken your senses with the robust flavor and aromatic richness of our American roast coffee, brewed to perfection.`,
        ingredients: `American Roast Coffee: Coffee`,
    },
    {
        id: 20,
        title: 'cappuccino',
        category: 'drinks',
        price: 5.99,
        img: 'https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_4:3/k%2FPhoto%2FRecipe%20Ramp%20Up%2F2022-07-Cappuccino%2FCappuccino',
        desc: `Indulge in the velvety smoothness and frothy perfection of our cappuccino, a comforting embrace in every sip.`,
        ingredients: `Whole Milk: Milk, Vitamin D3., Espresso Shot`,
    },
    {
        id: 21,
        title: 'espresso',
        category: 'drinks',
        price: 2.99,
        img: 'https://www.thespruceeats.com/thmb/HJrjMfXdLGHbgMhnM0fMkDx9XPQ=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/what-is-espresso-765702-hero-03_cropped-ffbc0c7cf45a46ff846843040c8f370c.jpg',
        desc: `Embrace the bold and intense flavors of our espresso, a quick shot of pure caffeinated bliss.`,
        ingredients: `The classic espresso: a single shot of espresso. ​Measure 1 scoop (1 tablespoon/9g) of beans for a single shot. Tamp horizontally and straight and place the watercup onto the (naked)portafilter. Fill 30 ml boiled water till first marker line (the ideal temperature for espresso is 95° C). The classic espresso: a single shot of espresso. ​Measure 1 scoop (1 tablespoon/9g) of beans for a single shot. Tamp horizontally and straight and place the watercup onto the (naked)portafilter. Fill 30 ml boiled water till first marker line (the ideal temperature for espresso is 95° C).`,
    },

];
export default menu;
